USE ESP15;

CREATE TABLE IF NOT EXISTS Genre (
    idGenre INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Genre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
    idAlbum INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    albumName VARCHAR(255) NOT NULL,
    dateReleased DATETIME
);

CREATE TABLE IF NOT EXISTS Artist (
    artistId INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    artistName VARCHAR(255) NOT NULL
);

SELECT * FROM Album;

SELECT * FROM Genre;

TRUNCATE TABLE Album;

SELECT * FROM artist;

INSERT INTO Genre(idGenre, Genre) VALUES
(NULL, 'ROCK'),
(NULL, 'POP'),
(NULL, 'R&B'),
(NULL, 'SOUL'),
(NULL, 'COUNTRY'),
(NULL, 'HIP-HOP'),
(NULL, 'JAZZ'),
(NULL, 'REGGAE'),
(NULL, 'FLAMENCO'),
(NULL, 'REGGAETON');

INSERT INTO Album(idAlbum, AlbumName, dateReleased) VALUES
(NULL, 'BÜCK DICH', '1998-02-24'),
(NULL, 'REPUTATION', '2016-04-30'),
(NULL, 'LOVE DELUX', '1992-10-20'),
(NULL, 'WHATS GOING ON', '1970-01-23'),
(NULL, 'COWBOY CARTER', '2024-04,29'),
(NULL, 'READY TO DIE', '1994-09-13'),
(NULL, 'KIND OF BLUE', '1959-08-17'),
(NULL, 'EXODUS', '1977-06-03'),
(NULL, 'DESPECHÁ', '2022-11-02'),
(NULL, 'TQG', '2023-10-30');

SELECT * FROM ALBUM;

INSERT INTO Artist(ArtistId, artistName) VALUES
(NULL, 'TILL LINDEMANN'),
(NULL, 'TAYLOR SWIFT'),
(NULL, 'SADE'),
(NULL, 'LOUIS AMSTRONG'),
(NULL, 'BEYONCE'),
(NULL, 'BIG NOTORIOUS'),
(NULL, 'MILES DAVID'),
(NULL, 'BOB MARLEY'),
(NULL, 'ROSALIA'),
(NULL, 'SHAKIRA');

SELECT * FROM ARTIST;


